apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webserver
  name: webserver
spec:
  volumes:
  - name: data-store
    persistentVolumeClaim:
      claimName: data-pvc
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: webserver
    volumeMounts:
       - name: data-store
         mountPath: /web
         